[package]
name = "poet"
version = "0.0.1"
authors = ["ve5li <ve5li@tuta.io>"]

[dependencies]
sfml = { git = "https://github.com/JeremyLetang/rust-sfml" }

[dependencies.seamonkey]
git = "https://github.com/vE5li/seamonkey.git"
features = ["tokenize", "parse"]
